# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve_date', models.DateTimeField(auto_created=True)),
                ('is_assignment', models.BooleanField(verbose_name='\u662f\u5426\u6bd4\u8d5b\u8bb0\u5f55')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trai.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('vid', models.IntegerField(primary_key=True, serialize=False)),
                ('oj', models.CharField(max_length=40)),
                ('pid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('submitted', models.IntegerField(blank=True, null=True)),
                ('solved', models.IntegerField(blank=True, null=True)),
                ('ac_rate', models.FloatField(blank=True, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('why_invalid', models.TextField(default='')),
                ('info_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='teams', to='Trai.Member')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trai.Problem'),
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='groups', to='Trai.Team'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(related_name='assignments', to='Trai.Group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='problems',
            field=models.ManyToManyField(related_name='assignments', to='Trai.Problem'),
        ),
    ]
