# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trai', '0002_auto_20170427_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.AlterField(
            model_name='history',
            name='is_assignment',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6bd4\u8d5b\u8bb0\u5f55'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='why_invalid',
            field=models.TextField(blank=True, default=''),
        ),
    ]
