# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trai', '0003_auto_20170427_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
    ]
