# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trai', '0004_auto_20170427_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='why_invalid',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
