# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trai', '0006_remove_assignment_end_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='contest',
            field=models.CharField(max_length=256, verbose_name='Contest Name'),
        ),
    ]
